using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Benzene.Azure.Function.SourceGenerators
{
    /// <summary>
    /// Emits the Azure Functions <c>[Function]</c>/<c>[…Trigger]</c> boilerplate class per transport
    /// from a user-authored assembly-attribute declaration (e.g.
    /// <c>[assembly: BenzeneHttpTrigger(Name = "orders", Route = "…")]</c>), forwarding each trigger
    /// invocation into the built <c>IAzureFunctionApp</c>. The user declares <em>what</em> triggers
    /// they want (and their bindings — route, queue, hub, …); the generator writes the ceremony.
    /// See <c>work/azure-functions-trigger-codegen-design.md</c>.
    /// </summary>
    [Generator]
    public class AzureFunctionTriggerGenerator : IIncrementalGenerator
    {
        internal const string HttpAttribute = "Benzene.Azure.Function.AspNet.BenzeneHttpTriggerAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // ForAttributeWithMetadataName is the efficient, incremental way to find (assembly-level)
            // attributes by type - each declared trigger flows through as a value-equatable TriggerInfo,
            // so an unchanged set of declarations short-circuits the cache.
            var http = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    HttpAttribute,
                    predicate: static (_, _) => true,
                    transform: static (ctx, _) => Http.Read(ctx))
                .SelectMany(static (items, _) => items);

            context.RegisterSourceOutput(http.Collect(), static (spc, triggers) => Execute(spc, triggers));
        }

        private static void Execute(SourceProductionContext context, ImmutableArray<TriggerInfo> triggers)
        {
            if (triggers.IsDefaultOrEmpty)
            {
                return;
            }

            // A function name must be unique across the app; a class name must be unique in the
            // generated namespace. Dedup deterministically so two declarations can't collide.
            var usedClassNames = new System.Collections.Generic.HashSet<string>();

            foreach (var trigger in triggers)
            {
                var className = Unique(usedClassNames, trigger.ClassName);

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("namespace Benzene.Azure.Function.Generated");
                sb.AppendLine("{");
                sb.AppendLine($"    public sealed class {className}");
                sb.AppendLine("    {");
                sb.AppendLine("        private readonly global::Benzene.Azure.Function.Core.IAzureFunctionApp _app;");
                sb.AppendLine($"        public {className}(global::Benzene.Azure.Function.Core.IAzureFunctionApp app) => _app = app;");
                sb.AppendLine();
                sb.AppendLine($"        [global::Microsoft.Azure.Functions.Worker.Function({trigger.FunctionNameLiteral})]");
                sb.AppendLine($"        public {trigger.ReturnType} Run(");
                sb.AppendLine($"            [{trigger.BindingAttribute}] {trigger.ParameterType} {trigger.ParameterName})");
                sb.AppendLine($"            => {trigger.DispatchExpression};");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }

        private static string Unique(System.Collections.Generic.HashSet<string> used, string candidate)
        {
            if (used.Add(candidate))
            {
                return candidate;
            }

            var i = 2;
            while (!used.Add(candidate + i))
            {
                i++;
            }

            return candidate + i;
        }
    }
}
