version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    expose:
      - 5432
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - "${TMPDIR:-/tmp/redis}:/tmp/redis"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: redis-server --requirepass yourpassword
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 127.0.0.1 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001"
    ports:
      - "10000:10000"
      - "10001:10001"
volumes:
  data01:
    driver: local