# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Benzene Http

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Benzene.Http/Benzene.Http.csproj
    - name: Build
      run: dotnet build Benzene.Http/Benzene.Http.csproj --no-restore
    - name: Test
      run: dotnet test Benzene.Http.Test/Benzene.Http.Test.csproj --no-build --verbosity normal
