# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Benzene Microsoft Dependencies

on:
  workflow_dispatch:
    inputs:    
      version:
        description: 'Version of the Nuget package'
        type: string
        required: true 
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Benzene.Microsoft.Dependencies/Benzene.Microsoft.Dependencies.csproj
    - name: Build
      run: dotnet build Benzene.Microsoft.Dependencies/Benzene.Microsoft.Dependencies.csproj --no-restore
    - name: Pack
      run: dotnet pack Benzene.Microsoft.Dependencies/Benzene.Microsoft.Dependencies.csproj -c Release -p:PackageVersion=${{ inputs.version }}
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/main')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
