#name: Deploy Azure Function Example
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#defaults:
#  run:
#    working-directory: ./Examples/Azure/Benzene.Example.Azure
#jobs:
#  build:
#    environment: test
#    runs-on: ubuntu-latest
#    env: 
#      working-directory: ./Examples/Azure/Benzene.Example.Azure
#
#    steps:
#    - name: Checkout code  
#      uses: actions/checkout@v2
#      
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 6.0.x
#        
#    - name: Restore dependencies
#      run: dotnet restore Benzene.Example.Azure.csproj
#      
#    - name: Build
#      run: dotnet build --no-restore Benzene.Example.Azure.csproj --configuration Release
#    
#    - name: 'Run Azure Functions action'
#      uses: Azure/functions-action@v1
#      with:
#        app-name: benzene-example
#        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 
