name: Deploy AWS Lambda Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./Examples/Aws/
jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    env: 
      working-directory: ./Examples/Aws/
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
      
    - name: Build
      run: dotnet build Benzene.Examples.Aws/Benzene.Examples.Aws.csproj
      
    - name: Deploy to Lambda
      run: dotnet lambda deploy-function -cfg Benzene.Examples.Aws/aws-lambda-tools-defaults.json
